{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "reference-nbi.serviceAccountName" . }}
  labels:
{{ include "reference-nbi.labels" . | indent 4 }}
{{- end -}}
