#FROM anapsix/alpine-java:jre8
FROM openjdk:8

ARG USERVICE_HOME=/opt/app/

# Build up the deployment folder structure
RUN mkdir -p $USERVICE_HOME

ADD reference-nbi-*.jar $USERVICE_HOME/lib/reference-nbi.jar
ADD startService.sh $USERVICE_HOME/bin/

CMD ["/opt/app/bin/startService.sh"]